
dependencies:
- alias: db
  name: mysql
  repository: https://kubernetes-charts.storage.googleapis.com
  condition: preview.mysql.enabled
  version: 0.10.1
- alias: expose
  name: exposecontroller
  repository: https://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.56
- alias: cleanup
  name: exposecontroller
  repository: https://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.56
- alias: preview
  name: node-http
  repository: file://../node-http
